repos:
    -   
        repo: https://github.com/pre-commit/mirrors-isort
        rev: v5.7.0
        hooks:
            - id: isort
    -
        repo: 'https://github.com/psf/black'
        rev: 20.8b1
        hooks:
            - id: black
              args: ['--safe']
    -
        repo: https://gitlab.com/PyCQA/flake8
        rev: 3.8.3
        hooks:
            - id: flake8
              args: [
                  # E501 let black handle all line length decisions
                  # W503 black conflicts with "line break before operator" rule
                  # E203 black conflicts with "whitespace before ':'" rule
                  '--ignore=E501,W503,E203']
    -
        repo: 'https://github.com/chewse/pre-commit-mirrors-pydocstyle'
        # 2.1.1
        rev: 22d3ccf6cf91ffce3b16caa946c155778f0cb20f
        hooks:
            - id: pydocstyle
              args: [
                 # Check for docstring presence only
                 '--select=D1',
                 # Don't require docstrings for tests
                 '--match=(?!test).*\.py']

    -   
        repo: https://github.com/pre-commit/mirrors-mypy
        rev: 'v0.782'
        hooks:
            -   id: mypy
                exclude: ^python_seed/template
                args: [--no-strict-optional, --ignore-missing-imports]