name: pybayts
channels:
  - conda-forge
  - nodefaults
dependencies:
  - seaborn>=0.11.1
  - iteration_utilities>=0.11.0
  - tqdm
  - fire
  - boto3
  - dask
  - descartes>=1.0.0 # necessary for geopandas plotting
  - earthaccess
  - geocube
  - geopandas
  - graphviz
  - hydra-core
  - ipywidgets
  - jupyterlab
  - lightning>=2.0.0
  - matplotlib
  - numpy>=1.21
  - pandas
  - pip
  - pyogrio
  - pystac-client
  - python>=3.8
  - python-graphviz
  - pytorch>=2.0.0
  - rasterio
  - rich
  - rioxarray
  - scikit-learn
  - seaborn
  - setuptools
  - stackstac
  - torchdata>=0.6.0
  - wandb
  - xbatcher
  - xstac
  - zen3geo