name: Tests

# On every pull request, but only on push to main
on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          sudo apt-get install -y git \
            gpg-agent \
            wget \
            curl \
            libpocl-dev \
            nodejs \
            libpq-dev

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox codecov pre-commit

      - name: Check pyopencl vendors
        run: |
          python -m pip install pyopencl
          ls /etc/OpenCL/vendors
          python ./test_pocl.py

      # Run tox using the version of Python in `PATH`
      - name: Tox
        run: tox -e py
        env:
          LDFLAGS: -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib

      # Run pre-commit (only for python-3.8)
      - name: run pre-commit
        if: matrix.python-version == 3.8
        run: pre-commit run --all-files

      - name: Upload Results
        if: success()
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: ${{ matrix.platform }}-${{ matrix.tox-env }}
          fail_ci_if_error: false
