name: Tests

# On every pull request, but only on push to main
on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-20.04
    container: developmentseed/pybaytsci:latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox codecov pre-commit

      - name: Check pyopencl vendors
        run: |
          python -m pip install pyopencl
          ls /etc/OpenCL/vendors
          python ./test_pocl.py

      # Run tox using the version of Python in `PATH`
      - name: Tox
        run: tox -e py

      # Run pre-commit
      - name: Pre-commit
        run: |
          pre-commit install --install-hooks
          pre-commit run --all-files

      - name: Upload Results
        if: success()
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: ${{ matrix.platform }}-${{ matrix.tox-env }}
          fail_ci_if_error: false
