name: Doc Generation

# On push or PR to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-20.04
    container: developmentseed/pybaytsci:latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox codecov pre-commit

      # Run tox using the version of Python in `PATH`
      - name: Tox
        run: tox -e py

      # Run pre-commit
      - name: Pre-commit
        run: |
          pre-commit install --install-hooks
          pre-commit run --all-files

      # Constantly generate and deploy docs during development
      - name: Generate Docs
        env:
          TOXENV: docs
        run: tox

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/docs
